# Generated by Django 5.0.1 on 2024-04-15 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('pic', models.FileField(upload_to='Agent_Images/')),
                ('address', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('pic', models.FileField(upload_to='Member_Images/')),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=50)),
                ('property_price', models.CharField(max_length=50)),
                ('property_location', models.CharField(max_length=50)),
                ('property_image', models.FileField(upload_to='Property_Images/')),
                ('property_description', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='PropertyOwner',
            fields=[
                ('phone', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('pic', models.FileField(upload_to='Owner_Images/')),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PropertyQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('type_of_property', models.CharField(max_length=50)),
                ('price_range', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField()),
                ('rating', models.CharField(default='★★★★★', max_length=5)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='www_app.property')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='www_app.propertyowner'),
        ),
        migrations.CreateModel(
            name='PortalAdmin',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='www_app.property')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='www_app.propertyowner')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
