# Generated by Django 5.0.1 on 2024-04-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySeeker',
            fields=[
                ('phone', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('pic', models.FileField(upload_to='Property_Images/')),
                ('address', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
