# Generated by Django 5.0.1 on 2024-04-16 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www_app', '0002_propertyseeker_alter_member_id_alter_member_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portaladmin',
            options={},
        ),
        migrations.RemoveField(
            model_name='portaladmin',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='portaladmin',
            name='created',
        ),
        migrations.RemoveField(
            model_name='portaladmin',
            name='property',
        ),
        migrations.RemoveField(
            model_name='portaladmin',
            name='updated',
        ),
    ]
