# Generated by Django 5.0.1 on 2024-04-17 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www_app', '0003_alter_portaladmin_options_remove_portaladmin_agent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='id',
            new_name='m_id',
        ),
        migrations.RenameField(
            model_name='portaladmin',
            old_name='id',
            new_name='pa_id',
        ),
    ]
