# Generated by Django 5.0.1 on 2024-04-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www_app', '0005_inquiry_delete_portaladmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyowner',
            name='type',
            field=models.CharField(default='owner', max_length=10),
        ),
        migrations.AddField(
            model_name='propertyseeker',
            name='type',
            field=models.CharField(default='seeker', max_length=10),
        ),
    ]
