# Generated by Django 5.0.1 on 2024-04-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www_app', '0006_propertyowner_type_propertyseeker_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='property',
        ),
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(default='User', max_length=50),
        ),
    ]
