# Generated by Django 5.0.1 on 2024-04-18 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www_app', '0007_remove_feedback_property_feedback_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
    ]
